language: python

# blocklist
branches:
  except:
  - master

python:
  - "2.7"
  - "3.6"

before_install:
  # proxy
  # proxyAuthMethod
  # emptyAuth
  - git config --global http.sslVersion tlsv1.1
  # sslCipherList
  - git config --global http.sslVerify false
  # sslCert
  # sslKey
  # sslCertPasswordProtected
  # sslCAInfo
  # sslCAPath
  # pinnedpubkey
  - git config --global http.sslTry true
  - git config --global http.noEPSV true
  # userAgent
  - git config --global http.followRedirects true

  - git config --global user.name Default Seadas User
  - git config --global user.email seadas-user@localhost

  - git config --list --show-origin

# command to install dependencies
install:
  - ./install_ocssw.py -v

before_script:
  - wget https://oceandata.sci.gsfc.nasa.gov/SeaDAS/seadas_benchmark.tar.gz
  - tar -xzvf seadas_benchmark.tar.gz

script:
  - cd benchmark && ./seadas_benchmark.bash
